from src.enums.player_type_enum import PlayerTypeEnum

PLAYER_1_TYPE: PlayerTypeEnum = PlayerTypeEnum.MOUSE
PLAYER_2_TYPE: PlayerTypeEnum = PlayerTypeEnum.CAT

PLAYER_WIDTH = 64
PLAYER_HEIGHT = 64

PLAYER_1_NAME = 'player1'
PLAYER_2_NAME = 'player2'

PLAYER_VELOCITY: float = 100
PLAYER_MAX_LIVES: int = 5

PLAYER_GAME_OBJECT_ORDER_IN_LAYER: int = 2
POWER_GAME_OBJECT_ORDER_IN_LAYER: int = 1
BLOCK_GAME_OBJECT_ORDER_IN_LAYER: int = 1
BOMB_ORDER_IN_LAYER: int = 2
EXPLOSION_ORDER_IN_LAYER: int = 3

BLOCK_SIZE: int = 32
DISPLAY_HEIGHT: int = 80

GAME_DURATION: int = 300

SCREEN_WIDTH: int = BLOCK_SIZE * 15
SCREEN_HEIGHT: int = DISPLAY_HEIGHT + BLOCK_SIZE * 11

PROBABILITY_SPAWN_POWER: float = 1

EXPLOSION_TIME: int = 3
EXPLOSION_RANGE: int = 1
KICK_RANGE: int = 4
BOMB_CDR: float = 2

DROP_BOMB_CDR: float = 0.2
EXPLOSION_DURATION: float = 1.0

NONE_STATUS_DURATION: float = float('inf')
IMMUNE_STATUS_DURATION: float = 3.0
DEAD_STATUS_DURATION: float = float('inf')

